### ISSUE TITLE
uniqueID should be reset when MAXINT is reached

### ISSUE THREAD

**Issue by Dexus** [Atlantis-Software/milterjs#1]
I think there's a bug in this module. Sooner or later uniqueID MAXINT will be reached and should be reset. Otherwise there will be problems later when further requests are received.

**Comment by atiertant** [comment]
you re right, after 9007199254740991, uniqueID shoud be reset...
[fixed it](https://github.com/Atlantis-Software/milterjs/commit/d136b599d6b0015b67a31d9f2bbbb90d669b1563)
