### ISSUE TITLE
Incomplete documentation for events?

### ISSUE THREAD

**Issue by Dexus** [Atlantis-Software/milterjs#2]
Where are the Header events documented?

Would you please complete the documentation?

**Comment by atiertant** [comment]
hi,
`eoh` event is documented in [events](https://github.com/Atlantis-Software/milterjs#events) section.
which one isn't documented ?

**Comment by Dexus** [comment]
Something like header and marcos ;) 

Von meinem iPhone gesendet

**Comment by atiertant** [comment]
do you mean content of headers and macros ?

**Comment by Dexus** [comment]
When you have eoh where is header documented?
I mean you should all events documented and not only some and also the object ob the context etc.
This will help other devs to create a functional milter with your module.

Von meinem iPhone gesendet

**Comment by atiertant** [comment]
well ! headers and macros are not milterjs specific ...
documentation about headers could be find in [RFC 2822](https://tools.ietf.org/html/rfc2822) and macros are sent by postfix and is documented at [postfix milter macros](http://www.postfix.org/MILTER_README.html#macros)

i could add these links and add some same code with debug messages.

**Comment by Dexus** [comment]
Maybe you don't want to understand me, but it's okay. Take a look at your module and think for yourself how you could document it better. Be objective and think as a developer who holds the module in his hands for the first time.

Thanks

**Comment by atiertant** [comment]
didn't understood, thanks !
