### ISSUE TITLE
utf-8 body

### ISSUE THREAD

**Issue by nowrap** [Atlantis-Software/milterjs#5]
Hello,
we found and solved an other issue today.

Within the body event the text of 8bit/utf-8 encoded mails gets "corrupted".

Responsible for this is the following code:
```
case SMFIC_BODY:
        call_hooks('body', data.toString('ascii'));
break;
```

It encodes the body to 7bit/ascii and removes umlauts and so on.
Removing the 'ascii' from the toString-method prevents this.

Regards
nowrap

**Comment by atiertant** [comment]
fixed by #6 thanks for your contribution
